[PR] Warning team switch + mail submit +
TC-netw4ppl/TC-netw4ppl-app pull request #167
Opened 2022-12-15 16:35 UTC by mathisfchx

### Description
Warning when team switch + sending emails
Refactor front for relations
+ bug fixs

See attached issues in the commits

2022-12-15 17:38 UTC, lduf requested changes

2022-12-15 17:38 UTC, lduf commented on Netw4ppl/app/src/main/res/values-fr/strings.xml
> +    <string name="team_change_message">Cela implique un nouveau formulaire pour créer des personnes, toutes les données actuellement non synchronisés stockées dans votre application seront perdues. V
```suggestion
    <string name="team_change_message">Cela implique un nouveau formulaire pour créer des personnes, toutes les données actuellement non synchronisées stockées dans votre application seront perdues. Vous pouvez ci dessous les sauvegarder en les envoyant par email.</string>
```

2022-12-15 17:38 UTC, lduf commented on Netw4ppl/app/src/main/res/values-fr/strings.xml
> +    <string name="team_change_send_mail">Envoyer mes anciennes données par mail</string>
```suggestion
    <string name="team_change_send_mail">Envoyer mes anciennes données par email</string>
```

2022-12-15 17:38 UTC, lduf commented on Netw4ppl/app/src/main/res/values-fr/strings.xml
> +    <string name="change_team_back_message">Avez vous envoyé vos datas par mail ?</string>
```suggestion
    <string name="change_team_back_message">Avez vous envoyé vos données par email ?</string>
```

2022-12-15 17:38 UTC, lduf commented on Netw4ppl/app/src/main/res/values-fr/strings.xml
> +    <string name="change_team_back_send_mail">Non, envoyer mes anciennes données par mail</string>
```suggestion
    <string name="change_team_back_send_mail">Non, envoyer mes anciennes données par email</string>
```

2022-12-15 17:38 UTC, lduf commented on Netw4ppl/app/src/main/res/values/strings.xml
> +    <string name="team_change_send_mail">Upload old data by mail</string>
```suggestion
    <string name="team_change_send_mail">Upload old data by email</string>
```

2022-12-15 17:38 UTC, lduf commented on Netw4ppl/app/src/main/res/values/strings.xml
> +    <string name="change_team_back_yes">Yes, delete old data + change team</string>
```suggestion
    <string name="change_team_back_yes">Yes, delete old data & change team</string>
```

2022-12-15 17:38 UTC, lduf commented on Netw4ppl/app/src/main/java/netw4ppl/ines/DisplayDetailsRelationActivity.java
> +        mFromTitle = (com.google.android.material.textfield.TextInputLayout) findViewById(R.id.relation_from_title);
#134 
-> use an array ?

2022-12-15 17:38 UTC, lduf commented on Netw4ppl/app/src/main/java/netw4ppl/ines/MainActivity.java
> +                intent.setData(Uri.parse("https://user-doc.netw4ppl.tech"));
Export to xml ?

2022-12-15 17:38 UTC, lduf commented on Netw4ppl/app/src/main/java/netw4ppl/ines/utils/SubmitData.java
> +                System.out.println(f.getAbsolutePath());
```suggestion
               
```

2022-12-15 17:39 UTC, lduf commented on Netw4ppl/app/src/main/java/netw4ppl/ines/MainActivity.java
> +                intent.setData(Uri.parse("https://user-doc.netw4ppl.tech"));
To do in #134

2022-12-15 17:40 UTC, lduf approved these changes, later dismissed
🌍

2022-12-16 08:06 UTC, mathisfchx commented on Netw4ppl/app/src/main/res/values/strings.xml
> +    <string name="change_team_back_yes">Yes, delete old data & change team</string>
```suggestion
    <string name="change_team_back_yes">Yes, delete old data + change team</string>
```

2022-12-16 08:08 UTC, lduf approved these changes
🌍

2022-12-16 08:56 UTC, merged